services:
  mysql:
    image: mysql
    container_name: trackwize-mysql
    environment:
      MYSQL_ROOT_PASSWORD: TrackWize@12345
      MYSQL_DATABASE: trackwize_db
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d   # Auto-load all .sql files here
      - ./mysql_data:/var/lib/mysql         # Persistent database data
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
